### ISSUE TITLE
'MediaManager' object has no attribute 'syncDelete'

### ISSUE THREAD

**Issue by JoeyCG** [rsimmons/voracious#41]
When trying to export a card over to Anki I continue to receive this message. Any thoughts on why this might be the case? I have been using Voracious for about 3 months and never encountered this issue. Ever since though, I have been unable to fix the problem. I have tried deleting all voracious and anki related files off my computer and reinstalling as well as restructuring how my cards are made but nothing seems to work. I'm still able to export cards if they don't contain image or audio. I'm not sure if this project is still being worked on, but I would appreciate any help. 

![MediaManagerBug](https://user-images.githubusercontent.com/37813191/78367234-5c6e7900-7587-11ea-9672-4a496ae3e0b0.png)

**Comment by WilsonNet** [comment]
I think the problem is with AnkiConnect itself, I tried using their example here:

https://foosoft.net/projects/anki-connect/index.html#media

And this is the result (Insomnia is the software). 
![image](https://user-images.githubusercontent.com/25280488/78848421-20ed0800-79e8-11ea-861e-a647bd48859d.png)


Edit: They already know about it, there is even a pull request.

https://github.com/FooSoft/anki-connect/issues/146

**Comment by JoeyCG** [comment]
Thanks for the help, really appreciate it!
