### ISSUE TITLE
Exporting to Anki fails when using Japanese in certain fields

### ISSUE THREAD

**Issue by chriskempson** [rsimmons/voracious#6]
![default](https://user-images.githubusercontent.com/473831/45533682-6e939580-b7f0-11e8-93de-6f6304fd706b.PNG)
Exporting to Anki fails when using Japanese in certain fields, if I use characters within the ASCII range it works as expected.

![default](https://user-images.githubusercontent.com/473831/45534914-9553cb00-b7f4-11e8-9db5-5eee8a073b64.PNG)

**Comment by rsimmons** [comment]
Thanks for the report. I've successfully exported cards with Japanese in various fields, and I haven't encountered this issue yet. Are you able to narrow it down at all? E.g. does it error on Japanese in any fields? Is it only in "Don't fill" fields? Is it perhaps due to the deck name having Japanese in it? In the meantime, I'll try some more to find the error on my end.

**Comment by chriskempson** [comment]
Finally figured out how to reproduce this issue. It occurs when trying to save duplicate content to a field marked as the "Sort Field".

**Comment by rsimmons** [comment]
Thanks for digging in to this. That's strange. When I do that, I get the (intended) error message "Error: cannot create note because it is a duplicate" in the same location that you get the "Error: 'ascii' codec ..." message.

That error message is being returned from the AnkiConnect plugin. That doesn't necessarily mean the bug is in AnkiConnect, but it makes me wonder. Are you using an up to date version of the plugin? And are you using Anki 2.0 or 2.1, and on what platform?

Also, I can provide you with a modified version of the AnkiConnect plugin that will log more details of the error, if you want to go that far.

**Comment by chriskempson** [comment]
Anki version is 2.0. As for the AnkiConnect version, couldn't find any version number in the source so I deleted whatever version I had and fetched the latest and I'm now seeing the "duplicate" message 😄

**Comment by chriskempson** [comment]
Just wanted to add, you also see this error if you've renamed a deck but not yet told Voracious about it.
